from .postprocess import PostProcess
from .postprocess_from_text import PostProcessFromText
from .postprocess_from_sents import PostProcessFromSents
from .postprocess_from_entities import PostProcessFromEntities
from .anonymizer import Anonymizer